@AddMember_HostAddress = http://localhost:8080

### Request for children
POST {{AddMember_HostAddress}}/addmember?name=Alejandra&lastname=Espinoza&birthyear=2020
Content-Type: application/json
Accept: application/json

### Reques for adults
POST {{AddMember_HostAddress}}/addmember?name=Pepe&lastname=Rodelo&birthyear=1999
Content-Type: application/json
Accept: application/json